// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeHolding.Server.Infrastructure;

#nullable disable

namespace PrimeHolding.Server.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeManagementDbContext))]
    [Migration("20230310143246_NullableForeightKeyOfWorkTaskToEmployee")]
    partial class NullableForeightKeyOfWorkTaskToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimeHolding.Server.Core.DepartmentFeature.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = new Guid("5ffe80f0-d6da-48c6-ae5b-5302faf2925e"),
                            Name = "Testing"
                        },
                        new
                        {
                            Id = new Guid("9555923e-5bfc-4089-83a8-ea2cc7894821"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("3f6662bd-7aa5-405a-88c4-f0f278e424e0"),
                            Name = "Human Resource"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e7349a3-4299-41b3-babb-3845c2c31650"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Email = "JohnDoe@gmail.com",
                            FullName = "John Doe",
                            MonthlySalary = 999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("3caf25d7-8621-4d7b-b6c7-02f2a7fe03cc"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Email = "JaneDoe@gmail.com",
                            FullName = "Jane Doe",
                            MonthlySalary = 1999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("7957bdc4-37c9-4109-ac7e-744f485442db"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Email = "RichardBranson@gmail.com",
                            FullName = "Richard Branson",
                            MonthlySalary = 899.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("338142b5-9ac3-4d27-a72c-ad3a4fbc86c2"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Email = "AdamSmith@gmail.com",
                            FullName = "Adam Smith",
                            MonthlySalary = 5999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("08a83b44-af87-4e1e-8fc6-40fdbd78ee8f"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Email = "WarrenBuffet@gmail.com",
                            FullName = "Warren Buffet",
                            MonthlySalary = 2999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("f96e5ed7-2c0a-4838-8fba-4ca7fcc96a2c"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Email = "LeoTolstoy@gmail.com",
                            FullName = "Leo Tolstoy",
                            MonthlySalary = 1499.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("9e43a78c-1fa3-494d-9610-ea9074e01e59"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("e1f9e884-5205-4098-8ea9-d1d77600a9e9"),
                            Email = "CharlesDarwin@gmail.com",
                            FullName = "Charles Darwin",
                            MonthlySalary = 2299.99m,
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.WorkTaskFeature.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.ToTable("WorkTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b7149eb-d741-4e24-ba35-21c2de62af7e"),
                            AssigneeId = new Guid("5e7349a3-4299-41b3-babb-3845c2c31650"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("74ef45f5-f42c-4294-893a-ad6e0e2d948c"),
                            AssigneeId = new Guid("5e7349a3-4299-41b3-babb-3845c2c31650"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work2"
                        },
                        new
                        {
                            Id = new Guid("709b579f-ebb5-45d2-b327-2fb53376f0b6"),
                            AssigneeId = new Guid("5e7349a3-4299-41b3-babb-3845c2c31650"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work3"
                        },
                        new
                        {
                            Id = new Guid("2bd1400e-5caa-4845-9ad0-ad12c9c064d5"),
                            AssigneeId = new Guid("3caf25d7-8621-4d7b-b6c7-02f2a7fe03cc"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work4"
                        },
                        new
                        {
                            Id = new Guid("76463beb-db7e-40a4-899a-f9d2fde8062c"),
                            AssigneeId = new Guid("3caf25d7-8621-4d7b-b6c7-02f2a7fe03cc"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work5"
                        },
                        new
                        {
                            Id = new Guid("e8ec89b9-04f8-48e7-9b2c-4f9f9a0cf65f"),
                            AssigneeId = new Guid("7957bdc4-37c9-4109-ac7e-744f485442db"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work6"
                        },
                        new
                        {
                            Id = new Guid("b399fd16-d0d6-4575-9a91-aad94e5fe528"),
                            AssigneeId = new Guid("7957bdc4-37c9-4109-ac7e-744f485442db"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work7"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", b =>
                {
                    b.HasOne("PrimeHolding.Server.Core.DepartmentFeature.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.WorkTaskFeature.Entities.WorkTask", b =>
                {
                    b.HasOne("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", "Assignee")
                        .WithMany("WorkTasks")
                        .HasForeignKey("AssigneeId");

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.DepartmentFeature.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", b =>
                {
                    b.Navigation("WorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
