// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeHolding.Server.Infrastructure;

#nullable disable

namespace PrimeHolding.Server.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeManagementDbContext))]
    [Migration("20230309151720_AddSeedingData")]
    partial class AddSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = new Guid("ea3a1d44-42df-4760-a7e4-0c1f51fdc453"),
                            Name = "Testing"
                        },
                        new
                        {
                            Id = new Guid("d5add2f0-6eaf-492d-9743-a0ee9393693e"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("9c232f11-0a60-46fc-95c3-8613488b2d42"),
                            Name = "Human Resource"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd7a30a2-09ba-4a11-82e5-8823f60cfbd1"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Email = "JohnDoe@gmail.com",
                            FullName = "John Doe",
                            MonthlySalary = 999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("ce2405e7-0138-4183-b60e-5800af3e69e4"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Email = "JaneDoe@gmail.com",
                            FullName = "Jane Doe",
                            MonthlySalary = 1999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("5910d9cf-52a1-4de4-9662-a5335f5bf506"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Email = "RichardBranson@gmail.com",
                            FullName = "Richard Branson",
                            MonthlySalary = 899.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("3563bafb-638d-4944-b3a0-3a4ab8b99cc5"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Email = "AdamSmith@gmail.com",
                            FullName = "Adam Smith",
                            MonthlySalary = 5999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("d2d6e078-6fc1-48ab-907b-7232f923654e"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Email = "WarrenBuffet@gmail.com",
                            FullName = "Warren Buffet",
                            MonthlySalary = 2999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("86fd9feb-3a57-4689-8a2e-dbfccdfb367c"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Email = "LeoTolstoy@gmail.com",
                            FullName = "Leo Tolstoy",
                            MonthlySalary = 1499.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("ee0d8839-1129-4e70-9621-175e200c7900"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("152dad6a-a746-4760-908a-47b3e7c28c61"),
                            Email = "CharlesDarwin@gmail.com",
                            FullName = "Charles Darwin",
                            MonthlySalary = 2299.99m,
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.ToTable("WorkTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e9480df-36d1-4ea5-affc-61828f79d1ad"),
                            AssigneeId = new Guid("dd7a30a2-09ba-4a11-82e5-8823f60cfbd1"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("82fc3f11-5a91-4ba0-93e0-0d1d3bb2c346"),
                            AssigneeId = new Guid("dd7a30a2-09ba-4a11-82e5-8823f60cfbd1"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("832ce9a5-91ad-40da-9a14-51d291e65e4f"),
                            AssigneeId = new Guid("dd7a30a2-09ba-4a11-82e5-8823f60cfbd1"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("201e0dc0-fde8-4e68-8f10-ddfa3fc3efb9"),
                            AssigneeId = new Guid("ce2405e7-0138-4183-b60e-5800af3e69e4"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("eba91129-5ca9-42de-a5d0-40d5059078dd"),
                            AssigneeId = new Guid("ce2405e7-0138-4183-b60e-5800af3e69e4"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("4e8f766f-3eff-4c1a-91b0-a72876d9cf3d"),
                            AssigneeId = new Guid("5910d9cf-52a1-4de4-9662-a5335f5bf506"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("bf92b02f-8549-473f-9982-d94db2b66335"),
                            AssigneeId = new Guid("5910d9cf-52a1-4de4-9662-a5335f5bf506"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Employee", b =>
                {
                    b.HasOne("PrimeHolding.Server.Infrastructure.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.WorkTask", b =>
                {
                    b.HasOne("PrimeHolding.Server.Infrastructure.Entities.Employee", "Assignee")
                        .WithMany("WorkTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Employee", b =>
                {
                    b.Navigation("WorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
