// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeHolding.Server.Infrastructure;

#nullable disable

namespace PrimeHolding.Server.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeManagementDbContext))]
    [Migration("20230310153310_NonNullableForeighKeyInWorkTask")]
    partial class NonNullableForeighKeyInWorkTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimeHolding.Server.Core.DepartmentFeature.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = new Guid("2f32540c-aa12-4046-aac6-30f9827d32b2"),
                            Name = "Testing"
                        },
                        new
                        {
                            Id = new Guid("81cd087e-e2a8-4e6f-a67a-d79b45f328f0"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("05a423bd-cafb-425e-8ec2-3d4033efb5ea"),
                            Name = "Human Resource"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd4b5ebd-60bf-40c5-ae6e-65cbc73c8c31"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Email = "JohnDoe@gmail.com",
                            FullName = "John Doe",
                            MonthlySalary = 999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("a0741b83-0cf2-4c98-98ad-edd4b5e88d15"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Email = "JaneDoe@gmail.com",
                            FullName = "Jane Doe",
                            MonthlySalary = 1999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("d648588d-37d8-498a-9568-fefd945ce57c"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Email = "RichardBranson@gmail.com",
                            FullName = "Richard Branson",
                            MonthlySalary = 899.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("71b95131-dc0e-4f64-b91a-c2911f1f55c9"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Email = "AdamSmith@gmail.com",
                            FullName = "Adam Smith",
                            MonthlySalary = 5999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("d8525d95-5332-4807-8ae1-6f9320cad620"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Email = "WarrenBuffet@gmail.com",
                            FullName = "Warren Buffet",
                            MonthlySalary = 2999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("2b5717b6-76d8-404e-92c4-ba4da7df7fad"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Email = "LeoTolstoy@gmail.com",
                            FullName = "Leo Tolstoy",
                            MonthlySalary = 1499.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("1717d7eb-4478-4249-b5c1-85aa450b2905"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("99d83d4b-bba7-4390-99c4-bb3997146da4"),
                            Email = "CharlesDarwin@gmail.com",
                            FullName = "Charles Darwin",
                            MonthlySalary = 2299.99m,
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.WorkTaskFeature.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.ToTable("WorkTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a70e355-0251-403e-b513-cbf7f588330e"),
                            AssigneeId = new Guid("bd4b5ebd-60bf-40c5-ae6e-65cbc73c8c31"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("62c01a71-a7f1-405b-b5d2-72feb15d3fe1"),
                            AssigneeId = new Guid("bd4b5ebd-60bf-40c5-ae6e-65cbc73c8c31"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work2"
                        },
                        new
                        {
                            Id = new Guid("5c37e614-cfb9-4e2f-8c16-8e3626218116"),
                            AssigneeId = new Guid("bd4b5ebd-60bf-40c5-ae6e-65cbc73c8c31"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work3"
                        },
                        new
                        {
                            Id = new Guid("b6a7af06-ca19-4448-a2e5-c733d7ba18b6"),
                            AssigneeId = new Guid("a0741b83-0cf2-4c98-98ad-edd4b5e88d15"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work4"
                        },
                        new
                        {
                            Id = new Guid("7acce4a2-712e-40b3-a80d-e1a4d8efeffa"),
                            AssigneeId = new Guid("a0741b83-0cf2-4c98-98ad-edd4b5e88d15"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work5"
                        },
                        new
                        {
                            Id = new Guid("d0319a4a-862a-4594-a8bd-5bf0e7719ea8"),
                            AssigneeId = new Guid("d648588d-37d8-498a-9568-fefd945ce57c"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work6"
                        },
                        new
                        {
                            Id = new Guid("0ecf61df-7b1d-4782-815a-049fca061f88"),
                            AssigneeId = new Guid("d648588d-37d8-498a-9568-fefd945ce57c"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work7"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", b =>
                {
                    b.HasOne("PrimeHolding.Server.Core.DepartmentFeature.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.WorkTaskFeature.Entities.WorkTask", b =>
                {
                    b.HasOne("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", "Assignee")
                        .WithMany("WorkTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.DepartmentFeature.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PrimeHolding.Server.Core.EmployeeFeature.Entities.Employee", b =>
                {
                    b.Navigation("WorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
