// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeHolding.Server.Infrastructure;

#nullable disable

namespace PrimeHolding.Server.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeManagementDbContext))]
    partial class EmployeeManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = new Guid("2f5b9d91-1a62-444a-82f8-b26b3c53680b"),
                            Name = "Testing"
                        },
                        new
                        {
                            Id = new Guid("751ec32c-1534-45a1-953b-6a080f6394d4"),
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("83a2a2be-7031-45af-8ce8-145a6e2e68ad"),
                            Name = "Human Resource"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86e06955-1ecd-4d11-a248-67c57b5f6339"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Email = "JohnDoe@gmail.com",
                            FullName = "John Doe",
                            MonthlySalary = 999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("fcfa58e2-4f24-4d71-95c2-c3c2cae00d85"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Email = "JaneDoe@gmail.com",
                            FullName = "Jane Doe",
                            MonthlySalary = 1999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("b3327152-4ae6-4068-86b4-1f9ecf3f59ad"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Email = "RichardBranson@gmail.com",
                            FullName = "Richard Branson",
                            MonthlySalary = 899.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("5622a2eb-9a38-454b-86f9-9384db98695a"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Email = "AdamSmith@gmail.com",
                            FullName = "Adam Smith",
                            MonthlySalary = 5999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("1a64b2a6-b4db-43fb-b25b-6299a041e4d3"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Email = "WarrenBuffet@gmail.com",
                            FullName = "Warren Buffet",
                            MonthlySalary = 2999.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("dcf7d38a-dcda-4b1f-aab2-dcec1704cf05"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Email = "LeoTolstoy@gmail.com",
                            FullName = "Leo Tolstoy",
                            MonthlySalary = 1499.99m,
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("370341a0-4478-4138-9d7b-2cca08678c6f"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("9c4197ff-5390-46d1-84f9-eb07cb18452e"),
                            Email = "CharlesDarwin@gmail.com",
                            FullName = "Charles Darwin",
                            MonthlySalary = 2299.99m,
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.WorkTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.ToTable("WorkTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95cb82ca-924b-4c94-9e59-7e0bee85d97e"),
                            AssigneeId = new Guid("86e06955-1ecd-4d11-a248-67c57b5f6339"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work1"
                        },
                        new
                        {
                            Id = new Guid("11bdf56d-d619-40ab-9245-b3f329509f0e"),
                            AssigneeId = new Guid("86e06955-1ecd-4d11-a248-67c57b5f6339"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work2"
                        },
                        new
                        {
                            Id = new Guid("0b04f496-91f7-4407-a05c-fe1788efe253"),
                            AssigneeId = new Guid("86e06955-1ecd-4d11-a248-67c57b5f6339"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work3"
                        },
                        new
                        {
                            Id = new Guid("8e96605b-d107-4110-a3cd-5a6b00e483da"),
                            AssigneeId = new Guid("fcfa58e2-4f24-4d71-95c2-c3c2cae00d85"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work4"
                        },
                        new
                        {
                            Id = new Guid("e0ef9124-317e-4bcd-a6a6-d0b5c8e3ab20"),
                            AssigneeId = new Guid("fcfa58e2-4f24-4d71-95c2-c3c2cae00d85"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work5"
                        },
                        new
                        {
                            Id = new Guid("67aee09e-f6a0-474b-88b5-154c2295d282"),
                            AssigneeId = new Guid("b3327152-4ae6-4068-86b4-1f9ecf3f59ad"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work6"
                        },
                        new
                        {
                            Id = new Guid("7dc8ef73-830a-44cb-9a10-33b74f7ffb02"),
                            AssigneeId = new Guid("b3327152-4ae6-4068-86b4-1f9ecf3f59ad"),
                            Completed = false,
                            Description = "Lorem ipsum",
                            DueDate = new DateTime(1, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Work7"
                        });
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Employee", b =>
                {
                    b.HasOne("PrimeHolding.Server.Infrastructure.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.WorkTask", b =>
                {
                    b.HasOne("PrimeHolding.Server.Infrastructure.Entities.Employee", "Assignee")
                        .WithMany("WorkTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PrimeHolding.Server.Infrastructure.Entities.Employee", b =>
                {
                    b.Navigation("WorkTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
